[versions]
jdk = "8"
kotlin = "1.9.10"
ktlint = "1.0.1"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.7.4"
ktlint = "org.jlleitschuh.gradle.ktlint:11.6.1"
maven-publish = "com.vanniktech.maven.publish.base:0.22.0" # max for jdk8
git-publish = "org.ajoberstar.git-publish:3.0.1" # max for jdk8
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# lint
rulebook-ktlint = "com.hendraanggrian.rulebook:rulebook-ktlint:0.5-SNAPSHOT"
# main
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlinpoet = "com.squareup:kotlinpoet:1.14.2"
# test
truth = "com.google.truth:truth:1.1.5"
