[versions]
jdk = "11"
kotlin = "1.9.20"
ktlint = "1.3.1"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.8.3"
ktlint = "org.jlleitschuh.gradle.ktlint:12.1.1"
maven-publish = "com.vanniktech.maven.publish.base:0.29.0"
git-publish = "org.ajoberstar.git-publish:4.2.2"
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# lint
rulebook-ktlint = "com.hanggrian.rulebook:rulebook-ktlint:0.1"
# main
kotlinpoet = "com.squareup:kotlinpoet:1.18.1"
# test
truth = "com.google.truth:truth:1.4.4"
