[versions]
jdk = "8"
kotlin = "1.7.20"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.6.1"
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
spotless = "com.diffplug.spotless:6.11.0"
maven-publish = "com.vanniktech.maven.publish.base:0.21.0"
git-publish = "org.ajoberstar.git-publish:3.0.1"
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# main
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlinpoet = "com.squareup:kotlinpoet:1.11.0"
# test
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.1.3"
